# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [1]:
import numpy as np

In [2]:
A = np.array([[1402,191], [1371,821],[949,1437],[147,1448]])
B = np.array([[1,2,3],[4,5,6]])
print("A=\n",A,"\nB=\n",B)

A=
 [[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]] 
B=
 [[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of $A$ and $B$ 

In [3]:
print('Shape of A:',np.shape(A),'\nShape of B:',np.shape(B))

Shape of A: (4, 2) 
Shape of B: (2, 3)


## 3. Print some of the elements from $A$: 
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [4]:
print(A[0,0],"\n",A[0,1],"\n",A[2,1],"\n",A[3,0])

1402 
 191 
 1437 
 147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10. 

In [5]:
C = np.zeros((3,3))
print("before random data:\n",C)

for i in range(0, np.shape(C)[0]):
    for j in range(0, np.shape(C)[1]):
        C[i,j] = np.random.randint(1,11)
print("after random data:\n",C)

before random data:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
after random data:
 [[2. 6. 6.]
 [5. 4. 5.]
 [2. 8. 9.]]


## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [6]:
def rand_2Dmatrix(shape):
    """shape must be a tuple (x,y)
    """
    matrix = np.zeros(shape)
    for i in range(0, np.shape(matrix)[0]):
        for j in range(0, np.shape(matrix)[1]):
            matrix[i,j] = np.random.randint(1,11)
    return matrix
F = rand_2Dmatrix((4,4))
G = rand_2Dmatrix((4,4))
H = F+G
print("Final output:\n",H)

Final output:
 [[ 9.  6. 11. 10.]
 [ 9. 15. 12. 17.]
 [15.  8.  3.  8.]
 [10.  8. 12. 12.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 